// <auto-generated />
using System;
using FormNutri_ES1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormNutri_ES1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906203839_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormNutri_ES1.Entities.RegistroAvaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AplicadorId")
                        .HasColumnType("int");

                    b.Property<int>("Classificacao")
                        .HasColumnType("int");

                    b.Property<bool>("ConsentimentoLGPD")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2");

                    b.Property<int>("PontuacaoEbia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AplicadorId");

                    b.ToTable("RegistroAvaliacoes");
                });

            modelBuilder.Entity("FormNutri_ES1.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FormNutri_ES1.Entities.RegistroAvaliacao", b =>
                {
                    b.HasOne("FormNutri_ES1.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AplicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FormNutri_ES1.Entities.MarcadorConsumo", "MarcadorConsumo", b1 =>
                        {
                            b1.Property<int>("RegistroAvaliacaoId")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoBebidasAdocadas")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoDoces")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoEmbutidos")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoFeijao")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoFrutas")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoMiojo")
                                .HasColumnType("int");

                            b1.Property<int>("ConsumoVerduras")
                                .HasColumnType("int");

                            b1.Property<string>("RefeicoesRealizadas")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("UsoTelaRefeicoes")
                                .HasColumnType("int");

                            b1.HasKey("RegistroAvaliacaoId");

                            b1.ToTable("RegistroAvaliacoes");

                            b1.WithOwner()
                                .HasForeignKey("RegistroAvaliacaoId");
                        });

                    b.OwnsOne("FormNutri_ES1.Entities.Respondente", "Respondente", b1 =>
                        {
                            b1.Property<int>("RegistroAvaliacaoId")
                                .HasColumnType("int");

                            b1.Property<string>("Escolaridade")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EstadoCivil")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Genero")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Idade")
                                .HasColumnType("int");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RacaCor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("RecebeBolsaFamilia")
                                .HasColumnType("bit");

                            b1.Property<string>("Religiao")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SituacaoEmprego")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RegistroAvaliacaoId");

                            b1.ToTable("RegistroAvaliacoes");

                            b1.WithOwner()
                                .HasForeignKey("RegistroAvaliacaoId");
                        });

                    b.OwnsOne("FormNutri_ES1.Entities.RespostaEbia", "RespostaEbia", b1 =>
                        {
                            b1.Property<int>("RegistroAvaliacaoId")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta1")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta2")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta3")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta4")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta5")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta6")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta7")
                                .HasColumnType("int");

                            b1.Property<int>("Pergunta8")
                                .HasColumnType("int");

                            b1.HasKey("RegistroAvaliacaoId");

                            b1.ToTable("RegistroAvaliacoes");

                            b1.WithOwner()
                                .HasForeignKey("RegistroAvaliacaoId");
                        });

                    b.Navigation("MarcadorConsumo")
                        .IsRequired();

                    b.Navigation("Respondente")
                        .IsRequired();

                    b.Navigation("RespostaEbia")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
